services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    restart: unless-stopped
    volumes:
      - ./clickhouse-init.sql:/docker-entrypoint-initdb.d/clickhouse-init.sql:ro
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  ingestion-api:
    build:
      context: .
      dockerfile: services/ingestion-api/Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "8080:8080"

  processing-svc:
    build:
      context: .
      dockerfile: services/processing-svc/Dockerfile
    depends_on:
      - nats
      - clickhouse
    environment:
      - NATS_URL=nats://nats:4222
      - CLICKHOUSE_DSN=clickhouse://default:@clickhouse:9000/default 

  query-api:
    build:
      context: .
      dockerfile: services/query-api/Dockerfile
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_DSN=clickhouse://default:@clickhouse:9000/default
      - NATS_URL=nats://nats:4222
    ports:
      - "8081:8081"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - ingestion-api
      - query-api
    ports:
      - "3000:80" 